title: Chujia's Homepage
description: > # this means to ignore newlines until "baseurl:"
  welcome to chujia's new homepage
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chujia Liu # add your name
author-img: portrait.png # add your photo
about-author: Software Developer, Gamer, Photographer # add description
github: halosernuf # add your Github handle
linkedin: chujia-liu # add your Linkedin handle
email: chujia.uf[at]gmail.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  # - jekyll-maps

maps:
  google:
    api_key: AIzaSyD4cPOKfcZj8ksek2Lsno4nD4SwkzQ8q_Y

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
